#!/bin/bash
### BEGIN INIT INFO
# Provides:          VRIOT
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog $remote_fs
# Default-Start:     2 3 4 5 
# Default-Stop:      0 1 6
# Description:       Vriot Services
### END INIT INFO


##########  IMPORTANT README.
# This script is for initalizing vriot services within a VM
# This file shall be placed in the /etc/init.d/ of base image
# Before placing the file the filename shall be changed to
# `vriot` in order for the `service vriot start` to function
# properly
##########


PORT=5216

function start {
    python /VRIOT/ops/scripts/entrypoint.py
}

function stop {
    curl localhost:5216/stop-vriot-service
}

function reset {
    stop
    start
}


case "$1" in
  start)
      start
      ;;
  stop)
      stop
      ;;
  reset)
      reset
      ;;
  *)
    echo "Usage: $0 {start|stop|reset}"
esac
