### GET

This endpoint MUST be used to get details of a devices defined under the tenant.

+ Request (application/vnd.api+json)

    + Headers

            Authorization: Basic BASE64(ACCESS TOKEN)
            Access-Control-Allow-Origin:'*'
            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

    + Body

            {
                "device_euid": "aa:bb:cc:dd:ee:ff:00:11",
                "device_name": "DeviceName",
                "gateway": "aa:bb:cc:dd:ee:ff",
                "gateway_lock": False,
                "association_mode": 0,
                "manufacturer": "ManufacturerName",
                "brand": "BrandName",
                "power_mode": 1,
                "battery_level": 75,
                "tags": [Tag1, Tag2],
                "network_type": 0,
                "device_type": 0,
                "device_sensors":
                [{
                    "sensor_id": "1234567890",
                    "function_id": 0x01,
                    "sensor_type": 0,
                    "capability":
                    {
                        "attribute_id1": {
                            "user_command": "State",
                            "configured_value": {on:1}
                        },
                        "attribute_id2": {
                            "user_command": "Color",
                            "configured_value": {red:0, blue:255, green:255}
                        }
                    }
                }],
                "created_on":"epoch timestamp",
                "updated_on":"epoch timestamp",
                "is_enabled":True
            }


<!-- include(../docs-reuseable/docs-401-response.apib) -->
