### POST

This endpoint MUST be used to add a IoT device.

+ Request (application/vnd.api+json)

    + Headers

            Authorization: Basic BASE64(ACCESS TOKEN)
            Access-Control-Allow-Origin:'*'
            Accept: application/vnd.api+json

    + Body

            {
                "device_euid": "aa:bb:cc:dd:ee:ff:00:11",
                "device_name": "DeviceName",
                "gateway": "aa:bb:cc:dd:ee:ff",
                "gateway_lock": False,
                "association_mode": 0,
                "manufacturer": "ManufacturerName",
                "brand": "BrandName",
                "tags": [Tag1, Tag2]
            }

+ Response 200 (application/vnd.api+json)

    + Body

            {
                "device_id":"123456789012",
                "created_on":"epoch timestamp",
                "is_enabled":True,
                "is_deleted":False
            }


<!-- include(../docs-reuseable/docs-401-response.apib) -->
