version: 2

jobs:
  build:
    machine: true

  dependencies:
    pre:
      - sudo apt-get install python-setuptools
      - easy_install awscli
      - pip install -r ops/requirements-txt
      - echo "sibymathew" >> /home/ubuntu/test/tarigopla
      - docker build -t "$DOCKER_BRANCH":"$CIRCLE_SHA1" .

  test:
    post:
      - docker run -d -p 5000:5000 -e "STORMPATH_ID=$STORMPATH_ID" -e "STORMPATH_SECRET=$STORMPATH_SECRET" -e "PUBNUB_PUBLISH=$PUBNUB_PUBLISH" -e "PUBNUB_SUBSCRIBE=$PUBNUB_SUBSCRIBE" "$DOCKER_BRANCH":"$CIRCLE_SHA1"; sleep 10

  deployment:
    elasticbeanstalk:
      branch: master
      commands:
        - docker login -e siby.math@gmail.com -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
        - docker push "$DOCKER_BRANCH":"$CIRCLE_SHA1"
        - python ops/xcloud_deploy.py -bbucket -axcloud-app -v"$CIRCLE_SHA1" -excloud-env -mstage
