version: 2
jobs:
  build:
    working_directory: /home/circleci
    machine: true
    steps:
      - checkout
      - run:
          name: install-boto
          command: 'pip install boto'
      - run:
          name: install-awscli
          command: 'pip install awscli'
      - run:
          name: install-pyinstaller
          command: 'pip install pyinstaller'
      - run:
          name: download-baseimage
          command: 'aws s3 cp s3://vriot/baseimages/vriot-disk.vmdk /home/circleci/vriot-disk.vmdk'
      - run:
          name: run-build-script
          command: 'python VRIOT/ops/scripts/build.py'
