### DELETE

This endpoint MUST be used to create an API Key Pair for an user.

+ Request (application/vnd.api+json)

    + Headers

            Authentication: Basic BASE64(SESSION TOKEN)
            Access-Control-Allow-Origin:'*'
            Accept: application/vnd.api+json

    + Body

            {
                "api_key": "API_KEY"
            }

+ Response 200 (application/vnd.api+json)


<!-- include(../docs-reuseable/docs-401-response.apib) -->
