### DELETE

This endpoint MUST be used to delete an already created user.

+ Request (application/vnd.api+json)

    + Headers

            Authentication: Basic BASE64(ACCESS TOKEN)
            Access-Control-Allow-Origin:'*'
            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

    + Body

            {
                "user_id":"123456789012",
                "last_updated":"epoch timestamp",
                "is_enabled":False,
                "is_deleted":True
            }

<!-- include(../docs-reuseable/docs-401-response.apib) -->
