### GET

This endpoint MUST be used to get the details of an user.

+ Request (application/vnd.api+json)

    + Headers

            Authentication: Basic BASE64(SESSION TOKEN)
            Access-Control-Allow-Origin:'*'
            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

    + Body

            {
                "user_id":"123456789012",
                "first_name":"FirstName",
                "last_name":"LastName",
                "company":"Company",
                "email":"email@email.com",
                "username":"UserName",
                "phone":"PhoneNumber",
                "directory_map":"default",
                "group_map":"guest",
                "email_verification":False,
                "email_success_verification":False,
                "welcome_email":False,
                "email_template":"JSONTemplate"
                "send_notification":"False",
                "notification_method":"[None]",
                "created":"epoch timestamp",
                "last_updated":"epoch timestamp",
                "is_email_verified":True,
                "is_enabled":True,
                "is_deleted":False
            }


<!-- include(../docs-reuseable/docs-401-response.apib) -->
