### GET

This endpoint MUST be used to get a list of users defined under the tenant.

+ Request (application/vnd.api+json)

    + Headers

            Authentication: Bearer BASE64(SESSION TOKEN)
            Access-Control-Allow-Origin:'*'
            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

    + Body

            {
                "group_id":"123456789012",
                "name":"GroupName",
                "role":"Role",
                "email_domain_blacklist":"[None]",
                "email_domain_whitelist":"[All]",
                "email_verification":False,
                "email_success_verification":False,
                "welcome_email":False,
                "email_template":"JSONTemplate"
                "created":"epoch timestamp",
                "last_updated":"epoch timestamp",
                "send_notification":"False",
                "notification_method":"[None]",
                "is_enabled":True,
                "is_deleted":False
            }


<!-- include(../../docs-reuseable/docs-401-response.apib) -->
