
## Group Group

Group APIs provide management of users who will manage the IoT infrastructure within a single tenant context.

The attributes of Group object are the following, 

+ `name` (string) : Unique group name identifier.
+ `role` (string) : Role attached to the group.

Optional attributes
+ `send_notification` : Toggle to enable/disable notification. `Default` False
+ `notification_method` : List all the modes of notification. `Default` email
+ `email_domain_blacklist`: Users from this domain will not be added to the group. `Default` ["None"]
+ `email_domain_whitelist`: Users from this domain only will be added to the group. `Default` ["All"]
+ `email_verfification` : Toggle to enable/disable email verification. `Default` False
+ `email_success_verification` : Toggle to enable/disable email success verification. `Default` False
+ `welcome_email` : Toggle to enable/disable welcome email. `Default` False
+ `email_template` : JSON structure of email template. `Default` /get/email_template_example.
+ `is_enabled` : Toggle to enable/disable the tenant. `Default` True
+ `is_revoked` : Toggle to enable/disable the tenant temp access. `Default` False 


### List All [/auth/v1/group]

<!-- include(get-group.apib) -->

### List [/auth/v1/group/{id}]

+ Parameters
    + id (string, required) ... Provide the group name.

<!-- include(get-group-id.apib) -->
