
# Group Device Scan

Device Scan APIs can be used to scan IoT device in the IoT network. After scanning Device Create API can be used to add a scanned IoT device.

## Scan [/app/v1/devicewindow?gateway={gateway}]

+ Parameters
    + gateway (string, optional) ... Provide gateway_id or gateway_uid.

<!-- include(post-device-open-window.apib) -->
