+ Response 401 (application/vnd.api+json)

    + Body

            {
                "errors":[ 
                    {
                        "status": 401,
                        "title":"Not Authorized",
                        "detail":"The Token provided is not valid token.",
                    }

                ]
            }