### POST

This endpoint MUST be used to create/register a tenant.

+ Request (application/vnd.api+json)

    + Headers
    
            Access-Control-Allow-Origin:'*'
            Accept: application/vnd.api+json

    + Body

            {
                "first_name":"FirstName",
                "last_name":"LastName",
                "company":"Company",
                "email":"email@email.com",
                "password":"Password",
                "phone":"PhoneNumber",
                "subscription_type":"Trial",
                "subscription_template":"JSONTemplate",
                "email_verification":False,
                "email_success_verification":False,
                "welcome_email":False,
                "email_template":"JSONTemplate"
                "is_enabled":True,
                "is_revoked":False,
            }

+ Response 200 (application/vnd.api+json)

    + Body

            {
                "idb":"Unique tenant identifier",
                "api_url":"http://api.iot.com/api_uri"
            }


<!-- include(../docs-reuseable/docs-401-response.apib) -->
