
# Group Gateway

Gateway APIs can be used to perform CRUD operations on a gateway.

The attributes of Gateway object are the following, 

+ `gateway_uid` (string) : Unique identifier for a gateway (mac-address).

Optional attributes
+ `gateway_name` (string) : User readable gateway name.
+ `gateway_iot_network_mode` (int) : Gateway IoT network mode. `Default` 4
    + Values
        + 0 - both
        + 1 - zigbee
        + 2 - ble
        + 3 - none
        + 4 - not defined
+ `network_type` (string) : IoT network type.
+ `set_radio_tx_power` (string): Provide the radio transmit power.
+ `set_radio_channel` (string): Provide the radio channel.
+ `set_devices_limit` (string): Maximum supported devices on a radio.
+ `tags` (list of string): Device tags. `Default` None
+ `is_enabled` : Toggle to enable/disable the tenant. `Default` True

Response only attributes
+ `get_radio_tx_power` (string): Radio transmit power as reported by gateway.
+ `get_radio_channel` (string): Radio operating channel as reported by gateway.
+ `get_devices_count` (string): Total device connected to the radio.
+ `ip` (string): Gateway's IP Address.
+ `mac` (string): Gateway's MAC Address.
+ `netmask` (string): Gateway's Netmask.
+ `gateway` (string): Gateway's default gateway.
+ `dns` (string): Gateway's DNS servers.
+ `gateway_device_list` (list): Device associated with this gateway. 
+ `gateway_state` (int): Present gateway state.
    + Values
        + 0 - provisioned
        + 1 - connected
        + 2 - disconnected
        + 3 - rebooted
+ `gateway_version` (string): Running version of the gateway.
+ `gateway_loglevel` (int): Gateway's running log level.
    + Values
        + 0 - LOG_EMERG
        + 1 - LOG_ALERT
        + 2 - LOG_CRIT
        + 3 - LOG_ERR
        + 4 - LOG_WARNING
        + 5 - LOG_NOTICE
        + 6 - LOG_INFO
        + 7 - LOG_DEBUG
+ `is_deleted` (bool str): Returned True if the gateway is deleted.
+ `created_on` (int): Epoch time of when this record is created.
+ `updated_on` (int): Epoch time of when this record is last updated.


## Create [/app/v1/gateway]

<!-- include(post-gateway.apib) -->
<!-- include(get-gateway.apib) -->

## List/Delete/Update [/app/v1/gateway/{id}]

+ Parameters
    + id (int, required) ... Provide the gateway_id or gateway_uid of the device.

<!-- include(delete-gateway-id.apib) -->
<!-- include(patch-gateway-id.apib) -->
<!-- include(get-gateway-id.apib) -->
