FORMAT: 1A
HOST: http://api.vriot-ruckus.com

# VRIOT API

Write about VRIOT API here.


<!-- include(docs-authentication/group-authentication.apib) -->
<!-- include(docs-tenant/group-tenant.apib) -->
<!-- include(docs-account/group-account.apib) -->
<!-- include(docs-gateway/group-gateway.apib) -->
<!-- include(docs-device/group-device.apib) -->
